[Details]
  Icon = "img/icon.png"
  Name = "Hegelmote"
  ID = "io.github.jacalz.hegelmote"
  Version = "0.6.0"
  Build = 2

[Migrations]
  fyneDo = true

[LinuxAndBSD]
  GenericName = "Hegel Amplifier Controller"
  Categories = ["Audio", "AudioVideo", "Network"]
  Comment = "Control your Hegel amplifier over IP for seamless music playback."
  Keywords = ["Hegel", "amplifier", "music", "audio", "control", "remote", "IP", "fyne"]
