[Details]
Icon = "assets/img/icon-512.png"
Name = "Hegelmote"
ID = "io.github.jacalz.hegelmote"
Version = "0.10.1"
Build = 9

[LinuxAndBSD]
GenericName = "Hegel Amplifier Remote"
Categories = ["Audio", "AudioVideo", "Network"]
Comment = "Control your Hegel amplifier remotely."
Keywords = ["Hegel", "amplifier", "music", "audio", "control", "remote", "fyne"]

[Migrations]
fyneDo = true
