[Details]
  Icon = "assets/img/icon.png"
  Name = "Hegelmote"
  ID = "io.github.jacalz.hegelmote"
  Version = "0.6.0"
  Build = 2

[Migrations]
  fyneDo = true

[LinuxAndBSD]
  GenericName = "Hegel Amplifier Remote"
  Categories = ["Audio", "AudioVideo", "Network"]
  Comment = "Control your Hegel amplifier remotely."
  Keywords = ["Hegel", "amplifier", "music", "audio", "control", "remote", "fyne"]
