[Details]
  Icon = "img/icon.png"
  Name = "Hegelmote"
  ID = "io.github.jacalz.hegelmote"
  Version = "0.5.0"
  Build = 1

[Migrations]
  fyneDo = true

# [LinuxAndBSD]
#   GenericName = "File Transfer"
#   Categories = ["Network", "FileTransfer", "P2P", "Utility"]
#   Comment = "Easy encrypted sharing of files, folders, and text between devices."
#   Keywords = ["magic-wormhole", "send", "receive", "sharing", "transfer", "fyne"]
#   ExecParams = "%F"
